"""initial

Revision ID: 2f689270d634
Revises: None
Create Date: 2016-08-22 16:55:58.446925

"""

# revision identifiers, used by Alembic.
revision = '2f689270d634'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terminalparameter')
    op.add_column('book', sa.Column('charge_starthahah', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_pile_sn'), 'pile', ['sn'], unique=True)
    op.drop_index('sn', table_name='pile')
    op.create_foreign_key(None, 'pile', 'book', ['started_by'], ['id'])
    op.create_foreign_key(None, 'pile', 'book', ['locked_by'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pile', type_='foreignkey')
    op.drop_constraint(None, 'pile', type_='foreignkey')
    op.create_index('sn', 'pile', ['sn'], unique=True)
    op.drop_index(op.f('ix_pile_sn'), table_name='pile')
    op.drop_column('book', 'charge_starthahah')
    op.create_table('terminalparameter',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=True),
    sa.Column('param', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('pile_sn', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('complete_timestamp', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
