"""haha

Revision ID: 786f1a60fa30
Revises: 2f689270d634
Create Date: 2016-08-22 17:03:19.144784

"""

# revision identifiers, used by Alembic.
revision = '786f1a60fa30'
down_revision = '2f689270d634'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'charge_starthahah')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('charge_starthahah', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
