"""empty message

Revision ID: d2590cd5b3e7
Revises: dd0f6ab29452
Create Date: 2016-08-26 14:06:38.001941

"""

# revision identifiers, used by Alembic.
revision = 'd2590cd5b3e7'
down_revision = 'dd0f6ab29452'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pile', sa.Column('configuration_rate', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('pile', sa.Column('configuration_status', sa.SmallInteger(), nullable=True))
    op.add_column('pile', sa.Column('upgrade_rate', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('pile', sa.Column('upgrade_status', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pile', 'upgrade_status')
    op.drop_column('pile', 'upgrade_rate')
    op.drop_column('pile', 'configuration_status')
    op.drop_column('pile', 'configuration_rate')
    ### end Alembic commands ###
