"""empty message

Revision ID: d347894495cb
Revises: f5bc21b2641b
Create Date: 2016-08-26 13:20:13.676308

"""

# revision identifiers, used by Alembic.
revision = 'd347894495cb'
down_revision = 'f5bc21b2641b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pile', sa.Column('configuration_rate', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('pile', sa.Column('configuration_status', sa.SmallInteger(), nullable=True))
    op.add_column('pile', sa.Column('upgrade_rate', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('pile', sa.Column('upgrade_status', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pile', 'upgrade_status')
    op.drop_column('pile', 'upgrade_rate')
    op.drop_column('pile', 'configuration_status')
    op.drop_column('pile', 'configuration_rate')
    ### end Alembic commands ###
