"""empty message

Revision ID: dd0f6ab29452
Revises: 0e297ce62a33
Create Date: 2016-08-26 13:57:59.738980

"""

# revision identifiers, used by Alembic.
revision = 'dd0f6ab29452'
down_revision = '0e297ce62a33'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pile', 'configuration_status')
    op.drop_column('pile', 'configuration_rate')
    op.drop_column('pile', 'upgrade_status')
    op.drop_column('pile', 'upgrade_rate')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pile', sa.Column('upgrade_rate', mysql.DECIMAL(precision=10, scale=3), nullable=True))
    op.add_column('pile', sa.Column('upgrade_status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('pile', sa.Column('configuration_rate', mysql.DECIMAL(precision=10, scale=3), nullable=True))
    op.add_column('pile', sa.Column('configuration_status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    ### end Alembic commands ###
