"""empty message

Revision ID: f5bc21b2641b
Revises: 786f1a60fa30
Create Date: 2016-08-26 13:18:13.594675

"""

# revision identifiers, used by Alembic.
revision = 'f5bc21b2641b'
down_revision = '786f1a60fa30'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pile', 'configuration_rate')
    op.drop_column('pile', 'upgrade_status')
    op.drop_column('pile', 'configuration_status')
    op.drop_column('pile', 'upgrade_rate')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pile', sa.Column('upgrade_rate', mysql.DECIMAL(precision=10, scale=3), nullable=True))
    op.add_column('pile', sa.Column('configuration_status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('pile', sa.Column('upgrade_status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('pile', sa.Column('configuration_rate', mysql.DECIMAL(precision=10, scale=3), nullable=True))
    ### end Alembic commands ###
